dist: trusty
sudo: required
before_install:
  - sudo add-apt-repository ppa:chris-lea/libsodium
  - sudo echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
  - sudo echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
  - sudo apt-get update && sudo apt-get install libsodium-dev
  - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
  - wget https://swift.org/builds/swift-3.0.2-release/ubuntu1404/swift-3.0.2-RELEASE/swift-3.0.2-RELEASE-ubuntu14.04.tar.gz
  - tar xzf swift-3.0.2-RELEASE-ubuntu14.04.tar.gz
  - export PATH=${PWD}/swift-3.0.2-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
script:
  - swift build
