os:
  - linux
  - osx

matrix:
  include:
    - env:
      - SWIFT_VERSION=3.1-RELEASE

language: generic

dist: trusty
sudo: required

osx_image: xcode8.3

addons:
  apt:
    sources:
      - sourceline: "ppa:chris-lea/libsodium"

before_install:
  - if [$TRAVIS_OS_NAME == "osx"]; then brew update; fi
  - if [$TRAVIS_OS_NAME == "osx"]; then brew install libsodium; fi

script:
  - swift build
