notifications:
  webhooks: https://azoy.gg/webhook/travis

language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install:
        - sudo -E add-apt-repository -y ppa:chris-lea/libsodium
        - sudo apt-get update && sudo apt-get install -y libsodium-dev
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/Azoy/a723677c6cdc891e9b0ab2df1fc1d018/raw/dd4104202deb7ba2af2b062a45e1d20aaa48f47e/swift-3.1-travis.sh)"
    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew update
        - brew install libsodium

script:
  - swift build
