language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - SWIFT_VERSION=https://swift.org/builds/swift-3.1-release/ubuntu1404/swift-3.1-RELEASE/swift-3.1-RELEASE-ubuntu14.04.tar.gz
      addons:
        apt:
          sources:
            - sourceline: "ppa:chris-lea/libsodium"
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew update
        - brew install libsodium

script:
  - swift build
