dist: trusty
sudo: required
before_install:
  - wget https://github.com/jedisct1/libsodium/releases/download/1.0.11/libsodium-1.0.11.tar.gz
  - tar xvfz libsodium-1.0.11.tar.gz
  - cd libsodium-1.0.11
  - ./configure --prefix=$HOME/libsodium
  - make
  - make install
  - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
  - wget https://swift.org/builds/swift-3.0.2-release/ubuntu1404/swift-3.0.2-RELEASE/swift-3.0.2-RELEASE-ubuntu14.04.tar.gz
  - tar xzf swift-3.0.2-RELEASE-ubuntu14.04.tar.gz
  - export PATH=${PWD}/swift-3.0.2-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
script:
  - swift build
